name: Download and Upload to Release

on:
  workflow_dispatch: 

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download file
        run: |
          mkdir -p ./dist
          curl -L -o ./dist/easydown-arm-1.3.38.fpk http://www.tswords.top/fpk/easydown-arm-1.3.38.fpk
          # 验证文件是否下载成功
          ls -lh ./dist/easydown-arm-1.3.38.fpk

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/easydown-arm-1.3.38.fpk
          asset_name: easydown-arm-1.3.38.fpk
          tag: 1.3.38
          overwrite: true
